* High Speed
 If you don't plunge the second ball at full speed after locking a ball, you only get a 2-ball multiball and everyone will make fun of you.

Re-light the kickback by shooting lit 1-6 target or a lit inlane. Alley passing the inlane is generally best as it also lights freeway orbit
general

Before plunging, bump the plunger and wait for the tachometer lights to settle. Then plunge up the ramp, the ramp will spot a target.
secret move

5 ramp shots on a single ball will give you the maximum bonus and hold bonus.

Both the ramp and the right eject hole spot standups. Both are much safer than shooting the standups themselves.

If you get a Jackpot and have all three balls still, shoot then second up the ramp and then shoot Freeways for zero-risk points.

Getting two lit Freeways lights all spinners for 1k/spin, which can really add up, especially in MB after the jackpot is scored.

Complete the green, yellow, then red standups to light MB on ramp (Getaway). The ramp also spots standups. Shoot ramp during MB for jackpot.

* Full Throttle
   Each Challenge mode started adds a ball into play and another lit shot, which could lead to an awesome 5-ball multiball frenzy!
multiball

When 2x, 3x, 4x etc is lit on the back wall, start playfield multiplier by pressing the launch button.

Repeatedly shoot ramps or orbits to start challenges, which are two ball multiballs with a very short ball save.

Light race roll overs on inlanes to enable race mode. Start race at scoop.

* Pinball Magic

  http://pinball.org/rules/pinballmagic.html

   On ball one, a full plunge will score the first trick, as it goes around the loop you can easily do a one timer up the ramp to lock ball 1

Short plunge the ball into the magic hat (awards 5M or will start "Mayhem" when lit).
skillshot

There is NO zero switch hit ball save on this game.

First "Matra Magna" (boss) trick, Silence Critics, can be done by rebound from post near magic hat, if it goes into lane and hits switches!

If struggling to complete a trick, hitting captive ball will eventually award "Spot Trick", spots it for you! Won't work on boss, though.

Try to memorize what each "magic trick" wants you to do, because it can be difficult to hear the sounds/voices in a noisy environment.

* Playboy

 UTAD via the right orbit from the left flipper and through the narrow gate left of the left bumper from the right flipper.  Shoot the center key standup target each time you finish the four top lane keys. 
 
 Go-To Flipper:  Balanced.

  https://soldmy.org/emguide/index.php/Playboy_(Bally,_1978)


* Most Haunted

   Prison mode is started by shooting left orbit repeatedly, then when mode starts shoot the 3 bank and ghost to add balls and score jackpots.

Prison mode and Hotel mode seem to be the most valuable for points because of multiplied jackpot values.

Backhanding from L flipper prison door during hospital ghost mode is safer than shooting from R flipper.

Move skill shot to pops and shoot there early and often. Two hardest ghost modes to start, and pop hits also increase jackpot values.

Recommend shooting all major shots 3x to have all ghosts 1 shot away at any time to start the game out, modes more valuable than MB.

There is a ball save coded into any ball coming out of the right scoop, don't flail away at balls coming from there and lose control.

Complete one minion before starting Hellavator MB, then at start of multiball shoot for center standup bank like crazy to stack minion MB.
multiball

In tournament , Hotel mode, the 3rd lit camera shot will always activate the MB. In regular play it his randomly 1 of the 5 camera shots.

Choose skill shot with flippers. Choose pops, ORB, or basement. Plunge to the selected shot.
Pops 750k
ORB 125k
Basement 1 Million

* Nine Ball

 Not really!  Loops, bonus, the spinner and the number sequence all can add good value.  “Hit what’s lit for its highest value” is a viable strategy.
 
 Go-To Flipper:  Balanced.
  
  https://soldmy.org/emguide/index.php/Nine_Ball_(Stern,_1980)


* Elektra

Hit flashing blue stand ups to collect Electra points. At least 6 enables valuable lower playfield time when you drain.   

* Dr Dude

http://pinball.org/rules/drdude.html

* Diner

Strategies
Hit right Ramp. Hit cup shot for 3.5M. Lock ball. Nail left ramp repeatedly to increase Dine-Time value and light extra ball. Release Ball. During multiball go for "Get the Rush". Serve the customers and get your prize. Repeat.
  
http://pinball.org/rules/diner.html  

* Party Animal 

Hit Saucers, Give You Letters, Upper Flipper to hit top ramp

* Avatar 

 Link and amp suit can be combined in either order.
multiball

Hitting the ball back into the "Link" shot within a few seconds of starting link multiball will add-a-ball
multiball

Link multiball super jackpot and double super are high value shots in the game. Top lanes light shot doublers...double link asap

Link MB: Shoot Link repeatedly to start. Shoot Link to trap/add ball. Hit 15 lit jackpots, then Link again for 3M (double-able) super.
multiball

Moving insert on A M P 3 bank motor targets will drop bank in one hit similar to pinbot/Spideman etc.

Completing top lanes lights shot doublers

Lighting Eywa mystery is switch-based (100-ish switches?). Eywa prioritizes add-time over add-a-ball in multiball. Eywa awards stack.

All modes can be stacked. Navi scoring must be ready (targets pulsing). Start seeds 1st, then Navi/Bomber/Banshee in any order, then mballs.

Stack Bomber Battle into Link or Amp for better points (Bomber maxes out at 1 mil a shot, with many shots always lit).

Amp Suit: Spell AMP then shoot revealed standups 4x. Fifth shot to bullseye starts MB. Lit shots for JPs & doubles, then bullseye is super.
multiball

Navi MB: Collect 6 chars then spell & shoot NAVI to start. After 6 JPs on red shots, spell NAVI for double JPs. Then super at unobt. target.

  

http://www.pinballnews.com/games/avatar/index5b.html  

* Baywatch
